version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "chore"
    include: "scope"  
  open-pull-requests-limit: 6
  ignore:
    # node-fetch must be synced manually
    - dependency-name: "node-fetch"
    - dependency-name: "release-it"
    - dependency-name: "@release-it/conventional-changelog"
    
