name: build

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4', '8.1' ]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    services:
      mysql:
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 33306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pdo, pdo_mysql, intl, zip
          coverage: none

      - name: Check PHP version
        run: php -v

      - name: Check Composer version
        run: composer -V

      - name: Check PHP extensions
        run: php -m

      - name: Check MySQL version
        run: mysql -V

      - name: Start MySQL
        run: sudo systemctl start mysql

      - name: Check MySQL variables
        run: mysql -uroot -proot -e "SHOW VARIABLES LIKE 'version%';"

      - name: Create database
        run: mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS slim_skeleton_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'

      - name: Copy settings
        run: cp config/env.github.php config/env.php

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies for PHP 7
        if: matrix.php-versions < '8.0'
        run: composer update --prefer-dist --no-progress

      - name: Install dependencies for PHP 8
        if: matrix.php-versions >= '8.0'
        run: composer update --prefer-dist --no-progress --ignore-platform-req=php

      - name: Install tables
        run: php vendor/bin/phoenix migrate

      - name: Run test suite
        run: composer check
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
